const express = require('express');
const router = express.Router();
const { getSession } = require('../data/sessionStore');
const { assessTestCases, readinessSummary } = require('../services/testCaseFeasibility');
const persistence = require('../services/persistenceService');
const behaviorRuleStore = require('../services/behaviorRuleStore');
const knowledgeStore = require('../services/behaviorRuleKnowledgeStore');
const { buildCanonicalElementRegistry } = require('../services/canonicalElementRegistry');
const { RULE_TYPES,RULE_SOURCES,SCOPE_TYPES,TRIGGERS,upsertRules,linkRulesToCase,discoveryRulesFromRegistry,mergeDiscoveredRules } = require('../services/behaviorRuleRegistry');

const AUTH_REQUIRED=String(process.env.AUTH_REQUIRED||'false').toLowerCase()==='true';
function qaManagerOnly(req,res,next){if(!AUTH_REQUIRED)return next();const role=String(req.user?.role||'').toUpperCase();if(!req.user)return res.status(401).json({reply:'Authentication is required.'});if(!['QA','MANAGER'].includes(role))return res.status(403).json({reply:'QA or MANAGER role is required.'});next();}
function safeRules(session){return Array.isArray(session.behaviorRules)?session.behaviorRules:[];}
function ensureRegistry(session){if(session.canonicalElementRegistry?.elements?.length)return session.canonicalElementRegistry;session.canonicalElementRegistry=buildCanonicalElementRegistry(session.pageDiscoveries||[]);return session.canonicalElementRegistry;}
async function loadSharedKnowledge(session){const shared=await knowledgeStore.load(session);if(shared.rules?.length){session.behaviorRules=shared.rules;session.behaviorRuleConflicts=shared.conflicts||[];}return shared;}
function syncDiscovery(session){const registry=ensureRegistry(session),discovered=discoveryRulesFromRegistry(registry),merged=mergeDiscoveredRules(safeRules(session),discovered);session.behaviorRules=merged.rules;const resolved=(session.behaviorRuleConflicts||[]).filter(c=>c.status==='RESOLVED');session.behaviorRuleConflicts=[...resolved,...merged.conflicts];return{discovered:discovered.length,conflicts:merged.conflicts.length};}
function relinkAndAssess(session){const registry=ensureRegistry(session);session.testCases=(session.testCases||[]).map(tc=>linkRulesToCase(tc,safeRules(session),registry));session.testCases=assessTestCases(session.testCases,{pageDiscoveries:session.pageDiscoveries||[],hasCredentials:Boolean(session.credentials?.username&&session.credentials?.password),actorCatalog:session.testActors||[],actorCredentialRefs:Object.entries(session.actorCredentials||{}).filter(([,c])=>c?.username&&c?.password).map(([ref])=>ref),story:session.story||''});session.automationReadiness=readinessSummary(session.testCases);session.readinessValidated=true;}
async function persist(sessionId,session,req){await knowledgeStore.save(session,session.behaviorRules||[],session.behaviorRuleConflicts||[]);if(!persistence.enabled())return;await persistence.persistSession(sessionId,session,{projectId:session.projectId,repositoryId:session.repositoryId,userId:req.user?.sub||session.createdBy||null});await persistence.persistTestCases(sessionId,session.testCases||[]);try{await behaviorRuleStore.persist(sessionId,session.behaviorRules||[],session.behaviorRuleConflicts||[],session.testCases||[]);}catch(err){console.error('[behavior-rules] session DB snapshot skipped',err.message);}}
function responseState(session,extra={}){return{ok:true,...extra,applicationKey:knowledgeStore.applicationKey(session),databaseMode:persistence.enabled()?'POSTGRESQL_AND_SESSION':'SESSION_ONLY',rules:safeRules(session),conflicts:session.behaviorRuleConflicts||[],automationReadiness:session.automationReadiness,testCases:(session.testCases||[]).map(tc=>({id:tc.id,title:tc.title,ruleRefs:tc.ruleRefs||[],effectiveRules:tc.effectiveRules||[],automationReadiness:tc.automationReadiness}))};}

router.get('/api/test-rules/catalog',qaManagerOnly,(_req,res)=>res.json({ok:true,ruleTypes:RULE_TYPES,sources:RULE_SOURCES,scopeTypes:SCOPE_TYPES,triggers:TRIGGERS}));
router.get('/api/test-rules/:sessionId',qaManagerOnly,async(req,res)=>{const session=getSession(req.params.sessionId||'default');try{if(!safeRules(session).length)await loadSharedKnowledge(session);res.json(responseState(session));}catch(err){res.status(422).json({ok:false,reply:err.message});}});
router.post('/api/test-rules/:sessionId/sync-discovery',qaManagerOnly,async(req,res)=>{const sessionId=req.params.sessionId||'default',session=getSession(sessionId);try{if(!safeRules(session).length)await loadSharedKnowledge(session);const sync=syncDiscovery(session);relinkAndAssess(session);await persist(sessionId,session,req);res.json(responseState(session,sync));}catch(err){res.status(422).json({ok:false,reply:err.message});}});
router.post('/api/test-rules/:sessionId',qaManagerOnly,async(req,res)=>{const sessionId=req.params.sessionId||'default',session=getSession(sessionId),incoming=Array.isArray(req.body?.rules)?req.body.rules:req.body?.rule?[req.body.rule]:[];if(!incoming.length)return res.status(422).json({ok:false,reply:'Provide at least one behavior rule.'});try{if(!safeRules(session).length)await loadSharedKnowledge(session);session.behaviorRules=upsertRules(safeRules(session),incoming,'USER_DEFINED');relinkAndAssess(session);await persist(sessionId,session,req);res.json(responseState(session));}catch(err){res.status(422).json({ok:false,reply:err.message});}});
router.post('/api/test-rules/:sessionId/import',qaManagerOnly,async(req,res)=>{const sessionId=req.params.sessionId||'default',session=getSession(sessionId),incoming=Array.isArray(req.body?.rules)?req.body.rules:[];if(!incoming.length)return res.status(422).json({ok:false,reply:'Imported rule list is empty.'});try{if(!safeRules(session).length)await loadSharedKnowledge(session);session.behaviorRules=upsertRules(safeRules(session),incoming.map(r=>({...r,source:'IMPORTED'})),'IMPORTED');relinkAndAssess(session);await persist(sessionId,session,req);res.json(responseState(session,{imported:incoming.length}));}catch(err){res.status(422).json({ok:false,reply:err.message});}});
router.post('/api/test-rules/:sessionId/conflicts/:conflictId/resolve',qaManagerOnly,async(req,res)=>{const sessionId=req.params.sessionId||'default',session=getSession(sessionId);if(!safeRules(session).length)await loadSharedKnowledge(session);const conflicts=session.behaviorRuleConflicts||[],conflict=conflicts.find(c=>c.conflictId===req.params.conflictId);if(!conflict)return res.status(404).json({ok:false,reply:'Rule conflict not found.'});const resolution=String(req.body?.resolution||'KEEP_APPROVED').toUpperCase();if(!['KEEP_APPROVED','ACCEPT_DISCOVERED'].includes(resolution))return res.status(422).json({ok:false,reply:'resolution must be KEEP_APPROVED or ACCEPT_DISCOVERED.'});if(resolution==='ACCEPT_DISCOVERED'){const existing=safeRules(session).find(r=>r.ruleId===conflict.ruleId);if(existing)session.behaviorRules=upsertRules(safeRules(session),[{...existing,value:conflict.discoveredValue,trigger:conflict.discoveredTrigger,source:'USER_DEFINED',approved:true}],'USER_DEFINED');}session.behaviorRuleConflicts=conflicts.map(c=>c.conflictId===conflict.conflictId?{...c,status:'RESOLVED',resolution,resolvedAt:new Date().toISOString()}:c);relinkAndAssess(session);await persist(sessionId,session,req);res.json(responseState(session,{resolution}));});

module.exports=router;
