<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../AITestPilot.Application/AITestPilot.Application.csproj" />
    <ProjectReference Include="../AITestPilot.Contracts/AITestPilot.Contracts.csproj" />
    <ProjectReference Include="../AITestPilot.Infrastructure/AITestPilot.Infrastructure.csproj" />
    <ProjectReference Include="../AITestPilot.AI/AITestPilot.AI.csproj" />
  </ItemGroup>
</Project>
