namespace AITestPilot.Domain.Testing;

public enum AssertionType
{
    ElementExists,
    ElementNotExists,
    ElementVisible,
    ElementHidden,
    ElementHiddenOrAbsent,

    TextEquals,
    TextContains,
    TextNotContains,
    TextEmpty,
    TextNonEmpty,
    HtmlEquals,
    HtmlContains,

    ValueEquals,
    ValueContains,
    ValueEmpty,
    ValueNonEmpty,
    ValueLengthEquals,
    ValueLengthLessThanOrEqual,
    ValueLengthGreaterThanOrEqual,
    Checked,
    Unchecked,
    Enabled,
    Disabled,
    Focused,
    Required,
    Optional,
    Html5Valid,
    Html5Invalid,
    SelectedValueEquals,

    AttributeExists,
    AttributeAbsent,
    AttributeEquals,
    AttributeContains,
    PropertyEquals,
    ClassPresent,
    ClassAbsent,
    CssValueEquals,
    PlaceholderEquals,
    AriaValueEquals,
    AccessibleNameEquals,
    AccessibleDescriptionEquals,

    CountEquals,
    CountMinimum,
    CountMaximum,

    UrlEquals,
    UrlIncludes,
    UrlNotIncludes,
    PathEquals,
    PathIncludes,
    QueryStringEquals,
    QueryStringIncludes,
    HashEquals,
    TitleEquals,
    TitleIncludes,

    CookieExists,
    CookieEquals,
    CookieAbsent,
    LocalStorageExists,
    LocalStorageEquals,
    LocalStorageAbsent,
    SessionStorageExists,
    SessionStorageEquals,
    SessionStorageAbsent,

    ResponseStatusEquals,
    ResponseStatusInRange,
    ResponseHeaderExists,
    ResponseHeaderEquals,
    ResponseBodyEquals,
    ResponseBodyContains,
    ResponseJsonPathEquals,
    RequestOccurred,
    RequestNotOccurred,
    RequestMethodEquals,
    RequestHeaderEquals,
    RequestBodyEquals,
    RequestBodyContains,
    RequestJsonPathEquals,
    RequestCountEquals,
    RequestDurationAtMost,

    NoAccessibilityViolations,
    NoCriticalAccessibilityViolations,
    MaximumAccessibilityViolations,

    FileDownloaded,
    FileNotDownloaded,
    FileNameEquals,
    FileNameContains,
    FileExists,
    FileSizeEquals,
    FileSizeMinimum,
    FileSizeMaximum,
    FileContentEquals,
    FileContentContains,
    JsonFilePathEquals,

    PageLoadAtMost,
    DomContentLoadedAtMost,
    FirstByteAtMost,
    ResourceLoadAtMost,
    ApiResponseAtMost,
    TotalTransferSizeAtMost,
    WebVitalAtMost,

    NewWindowOpened,
    NewWindowNotOpened,
    NewWindowUrlEquals,
    NewWindowUrlContains,
    NewWindowTitleEquals,
    NewWindowCountEquals,

    NoConsoleErrors,
    NoPageErrors,
    NoFailedRequests,
    NoHttp500Responses,
    MaximumConsoleWarnings
}
