<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <ProjectReference Include="../AITestPilot.Application/AITestPilot.Application.csproj" />
    <ProjectReference Include="../AITestPilot.Infrastructure/AITestPilot.Infrastructure.csproj" />
    <ProjectReference Include="../AITestPilot.Playwright/AITestPilot.Playwright.csproj" />
    <ProjectReference Include="../AITestPilot.AI/AITestPilot.AI.csproj" />
  </ItemGroup>
</Project>
